# Generated by Django 4.1.6 on 2023-02-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rank',
            name='id',
        ),
        migrations.AlterField(
            model_name='rank',
            name='rank_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
