# Generated by Django 4.1.6 on 2023-02-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_rank_id_alter_rank_rank_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='games',
            field=models.CharField(default='Nieznane', max_length=25),
        ),
        migrations.AlterField(
            model_name='rank',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
