# Generated by Django 4.1.6 on 2023-02-21 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0003_alter_rank_games_alter_rank_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='games',
            field=models.CharField(default='Nieznane', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='rank',
            name='score',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rank',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
