# Generated by Django 4.1.6 on 2023-02-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_rank_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='user',
            field=models.CharField(default='AnonymousUser', max_length=155, null=True),
        ),
    ]
