# Generated by Django 4.1.6 on 2023-02-21 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_rank_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rank',
            unique_together=set(),
        ),
    ]
